version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lambda_code
      - zip -r9 deployment_package.zip .
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://aws-e-commerce-data/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name aws-e-commerce-lambda --s3-bucket aws-e-commerce-data --s3-key deployment_package.zip
      - echo "Deployment complete!"